Bibliotech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Pages for everyone (even guests)
    path('', include('home.urls')),

    # User pages
    path('user/', include('user.urls')),

    # For login using all-auth (OAuth2)
    path('accounts/', include('socialplatform.urls')),

    # Moderator pages
    path('mod/', include('moderator.urls')),

    # Admin (Control) pages
    path('control/', include('control.urls')),

    # Default django admin page
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    
handler404 = 'home.views.handling_404'

home/urls.py
from django.contrib import admin
from django.urls import path,include
from home.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'
urlpatterns = [
    path('', indexView.as_view(), name='index'),
    path('dashboard', dashboardView.as_view(), name="dashboard"),
    path("gallery", galleryView.as_view(), name="gallery"),
    path('gallery/bookid=<int:id>/detail',bookView.as_view(), name="book"),
    path('gallery/bookid=<int:id>/pdf', bookPDFView.as_view(), name="bookPDF"),
    path('shelf/userid=<int:id>',shelfView.as_view(), name = "shelf"),
    path('borrow/bookid=<int:id>',borrowView.as_view(), name = "borrow"),
    path('faq', faqView.as_view(), name='faq'),
    path('contact', contactView.as_view(), name='contact'),
    path('result', resultView.as_view(), name='result'),
]

moderator/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "mod"
urlpatterns = [
    path("", modView.as_view(), name='mod'),
    path("addBook", addBookView.as_view(), name='addBook'),
    path('editBook/bookid=<int:id>', editBookView.as_view(), name='editBook'),
    path('addCopy/bookid=<int:id>', addCopyView.as_view(), name='addCopy'),
    path('editCopy/copyid=<int:id>', editCopyView.as_view(), name="editCopy"),
    path('apply', applyModView.as_view(), name="modApply"),
    path('modManage',modManageView.as_view(), name="modManage_get"),
    path('modManage/<int:id>',modManageView.as_view(), name="modManage_post"),
    path('adminManage',adminManageView.as_view(), name="adminManage"),
    path('adminManage/<int:id>',adminManageView.as_view(), name="adminManage_post"),
    path('deleteBook/bookid=<int:id>',deleteBook,name='deleteBook'),
    # Do not uncomment "import"
    # This function is only used to automatically add book
    # path('import', importDataView.as_view(), name="import"),
]




if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, reverse_lazy
from user.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'
urlpatterns = [
    path('register/', registerView.as_view(), name="register"),
    path('login/', loginView.as_view(), name='login'),
    path('logout/', logoutView.as_view(), name='logout'),
    path("password", changePasswordView.as_view(), name="changePassword"),

    path("recover", recoverAccountView.as_view(), name="recover"),
    path("recover/sent", recoverDoneView.as_view(), name="recover_done"),
    path("recover/<uidb64>/<token>", recoverConfirmView.as_view(), name="recover_confirm"),
    path("recover/complete", recoverCompleteView.as_view(), name="recover_complete"),

    path("profile/info/", profileInfoRedirectView.as_view(), name="info"),
    path("profile/userID=<int:id>/", profileInfoView.as_view(), name="wall"),
    path("profile/borrow/", userBorrowanceManagerView.as_view(), name="borrow"),
    path("profile/edit/", profileEditView.as_view(), name="edit"),
    path("activate/<uidb64>/<token>", activate, name="activate"),
]

if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

# Create your models here.
def getBookImageURL(instance, filename):
  if instance.id != None:
      return "book/{}/coverImage.png".format(instance.id)
  else:
    queryset = Book.objects.all().order_by('pk')
    last = queryset.last()
    last_id = last.id
    file_number = last_id+1
    return "book/{}/coverImage.png".format(file_number)

def getBookPDFURL(instance, filename):
  if instance.id != None:
      return "book/{}/pdfFile.pdf".format(instance.id)
  else:
    queryset = Book.objects.all().order_by('pk')
    last = queryset.last()
    last_id = last.id
    file_number = last_id+1
    return "book/{}/pdfFile.pdf".format(file_number)

def getUserImageURL(instance, filename):
  if instance.id != None:
      return "user/{}/avatar.png".format(instance.id)
  else:
    queryset = User.objects.all().order_by('pk')
    last = queryset.last()
    last_id = last.id
    file_number = last_id+1
    return "user/{}/avatar.png".format(file_number)

class User(AbstractUser):
  email = models.EmailField(null=False, blank=False, unique=True, help_text="Required", error_messages="This field is compulsory and must follow email format")
  avatar = models.ImageField(upload_to=getUserImageURL, null=True, blank=True)
  birthdate = models.DateField(null=True, blank=True)
  genderChoices = (
    (0, "male"),
    (1, "female"),
    (2, "other")
  )
  gender = models.IntegerField(choices=genderChoices, null=False, default=2)
  address = models.CharField(max_length=200, null=True, blank=True)
  phoneNum = models.CharField(max_length=50, null=True, blank=True)
  roleChoices = (
    (0, "user"),
    (1, "moderator"),
    (2, "admin"),
    (3, "banned")
  )
  role = models.IntegerField(choices=roleChoices, default=0)
  description = models.CharField(max_length=1500, null=True, blank=True)
  availableWorkingHours = models.CharField(max_length=300, null=True, blank=True)

class Book(models.Model):
  title = models.CharField(max_length=200, null=False, default="UNTITLED")
  author = models.CharField(max_length=200, null=False, default="UNKNOWN")
  typeChoices = (
    (0, "article"),
    (1, "book"),
    (2, "magazine"),
    (3, "video/audio"),
    (4, "comic"),
    (5, "other")
  )
  type = models.IntegerField(choices=typeChoices, null=True, default=0)
  liteCate = models.BooleanField(default=False, blank=True, null=True)
  socieCate = models.BooleanField(default=False, blank=True, null=True)
  naturCate = models.BooleanField(default=False, blank=True, null=True)
  techCate = models.BooleanField(default=False, blank=True, null=True)
  poliCate = models.BooleanField(default=False, blank=True, null=True)
  romanCate = models.BooleanField(default=False, blank=True, null=True)
  enterCate = models.BooleanField(default=False, blank=True, null=True)
  otherCate = models.BooleanField(default=False, blank=True, null=True)
  language = models.CharField(max_length=200, null=True, blank=True)
  description = models.TextField(max_length=1500, null=True, blank=True)
  coverImage = models.ImageField(upload_to=getBookImageURL, null=True, blank=True)
  pdfFile = models.FileField(upload_to=getBookPDFURL,null=True,blank=True)
  publisher = models.CharField(max_length=200, null=True, blank=True)
  publication = models.CharField(max_length=50, null=True, blank=True)
  codeISBN = models.CharField(max_length=50, null=True, blank=True)
  statusChoices = (
    (0, "pending"),
    (1, "accepted"),
    (2, "rejected")
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=True)
  id = models.AutoField(primary_key=True)
  manual = models.BooleanField(default=True, null = True, blank = True)

  def __str__(self) :
    return str(self.id) + ". " + self.title


class Copy(models.Model):
  bookID = models.ForeignKey(Book, null=False, on_delete=models.CASCADE)
  userID = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
  statusChoices = (
    (0, "hidden"),
    (1, "available"),
    (2, "borrowed"),
    (3, "unavailable")
  )
  status = models.IntegerField(choices=statusChoices, default=0)
  note = models.TextField(max_length=200, null=True, blank=True)
  regDate = models.DateTimeField(null=False)

  def __str__(self) :
    return str(self.id) + ". " + self.bookID.title


class Borrowance(models.Model):
  copyID = models.ForeignKey(Copy, on_delete=models.CASCADE)
  userID = models.ForeignKey(User, on_delete=models.CASCADE)
  borrowDate = models.DateTimeField(null=False)
  expiredDate = models.DateTimeField(null=False)
  statusChoices = (
    (0, "request"),
    (1, "double-check"),
    (2, "borrowing"),
    (3, "returned"),
    (4, "overdue"),
    (5, "lost")
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=False)
  deposit = models.FloatField(default=0, null=True, blank=True)


class Review(models.Model):
  bookID = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='reviews')
  userID = models.ForeignKey(User, on_delete=models.CASCADE)

  def validateRating(value):
    if (value > 5 or value < 1):
      raise ValidationError(
        _('%(value)s is not valid'),
        params={'value': value},
      )
    
  rating = models.IntegerField(validators=[validateRating], null=True, blank=True)
  review = models.TextField(max_length=1500, null=True, blank=True)
  created_at = models.DateTimeField(default=timezone.now)

  def __str__(self) :
    return "Review " + str(self.id)
  
def getApplicantDocURL(instance, filename):
  return "user/{}/modApplication.pdf".format(instance.applicant.id)

class ModApplication(models.Model):
  applicant = models.ForeignKey(User, on_delete=models.CASCADE)
  applicantDocument = models.FileField(upload_to=getApplicantDocURL,null=True,blank=True)
  applicantText = models.TextField(max_length=1500, null=True, blank=True)
  adminComment = models.TextField(max_length=1500, null=True, blank=True)
  statusChoices = (
    (0, "applying"),
    (1, "approved"),
    (2, "denied"),
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=False)
  created_at = models.DateTimeField(default=timezone.now)
  
class Thought(models.Model):
  userID = models.ForeignKey(User, on_delete=models.CASCADE)
  thought = models.TextField(max_length=1500, null=False)
  created_at = models.DateTimeField(default=timezone.now)
  
class BookApplication(models.Model):
  bookID = models.ForeignKey(Book, on_delete=models.CASCADE)
  uploader = models.ForeignKey(User, on_delete=models.CASCADE)
  statusChoices = (
    (0, "applying"),
    (1, "approved"),
    (2, "denied"),
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=False)
  created_at = models.DateTimeField(default=timezone.now)

home/forms.py
from typing import Any, Mapping
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from django.core.exceptions import ValidationError
from django.contrib import messages
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'

    def clean(self):
        rating = self.cleaned_data.get('rating')
        review = self.cleaned_data.get('review')
        print(rating)
        print(review)
        if (rating is None and review == ""):
            raise ValidationError("Email exists")
        return self.cleaned_data
    
    

templates/home/book.html
{% extends 'base/base.html' %}

{% block content %}
{% load static %}
{% include 'base/message.html' %}
<link href="{% static 'book/final-teamplate.webflow.6f28bf78a.css' %}"  rel="stylesheet" type="text/css" />

     <div class="main-section---user-profile">
        <div class="container-default w-container">
          <div class="block-sticky-top---main-contain---single-book">
            <div class="w-layout-grid brix---grid-2-columns-gap-column-80px">
              <div id="w-node-_5a17ac72-1850-1981-dc72-26f836fd84b8-7467042b" class="single-book---book-cover">
                <div class="brix---mg-bottom-32px-3">
                  <div class="brix---image-wrapper-br-24px-shadow">
    
                    

                    {% if book.coverImage %}          
                      {% if book.manual == True  %} 
                      <img src="{{ book.coverImage.url }}" alt="" class="brix---book-cover" />
                
                      {% else %}   
                      <img src="{{ book.coverImage }}" alt="" class="brix---book-cover" />
                
                      {% endif %}                 
                    {% else %}   
                    <img src="/media/book/defaultCover.jpg" alt="" class="brix---book-cover" />         
       
                    {% endif %}  

                  </div>
                </div>
              </div>
              <div id="w-node-_743cabc5-f3ec-dfd2-c79f-f1cd26c67777-7467042b" class="div-block-100">
                <div class="brix---mg-bottom-8px-4">
                  <div class="brix---color-neutral-816">
                    <h3 class="single-book---book-title">{{book.title}}</h3>
                  </div>
                </div>
                <div class="brix---mg-bottom-40px-6">
                  <div class="brix---color-neutral-815">
                    <p class="single-book---author"><strong>Author</strong>: {{ book.author }}</p>
                    <p class="single-book---author"><strong>Publisher</strong>: {{ book.publisher }}</p>
                    <p class="single-book---publish-year"><strong>Publication</strong>: {{ book.publication }}</p>
                    <p class="single-book---author"><strong>Language</strong>: {{ book.language }}</p>
                    <p class="single-book---provider">
                        <strong>Provider</strong>: 
                        <span id="selectedProvider">
                            <a href="#">{{ providers.0.userID__first_name }}</a> 
                            ({{ providers.0.amount_copies }} copies available)
                        </span>
                        <button class="toggle-button" onclick="toggleDropdown()">▼</button>
                        <div id="providerDropdown" class="dropdown-content">
                            {% for provider in providers %}
                                <a href="#" style = "margin-left: 80px;"
                                   onclick="selectProvider('{{ provider.userID__first_name }}', '{{ provider.amount_copies }}', '{{ provider.userID__id }}', '{{ provider.userID__address }}')">
                                   {{ provider.userID__first_name }} ({{ provider.amount_copies }} copies)
                                </a>
                                <br>
                            {% endfor %}
                        </div>
                    </p>
                    <p class="single-book---author"><strong>Location</strong>: <span id="providerLocation">{{ providers.0.userID__address }}</span></p>
                    <p class="single-book---description"><strong>Description</strong>: {{ book.description }}</p>
                  </div>
                
                <script>
                    function toggleDropdown() {
                        var dropdown = document.getElementById("providerDropdown");
                        dropdown.style.display = dropdown.style.display === "block" ? "none" : "block";
                    }
                
                    function selectProvider(name, amountCopies, id, location) {
                        // Update provider name and copies available
                        var selectedProvider = document.getElementById("selectedProvider");
                        selectedProvider.innerHTML = '<a href="/home/shelf/' + id + '">' + name + '</a> (' + amountCopies + ' copies available)';
                
                        // Update provider location
                        var providerLocation = document.getElementById("providerLocation");
                        providerLocation.textContent = location;

                        var modIdInput = document.getElementById("modId");
                        modIdInput.value = id;
                
                        // Hide the dropdown
                        toggleDropdown();
                    }
                </script>
                
                  <div class="button-container" style="padding-top: 2vw;">
                    <form method="post" action="{% url 'home:borrow' book.id%}" style="display: inline-block;">
                      {% csrf_token %}
                          <div class="block-of-check-out-button" >
                            <input type="hidden" name="book_id" value="{{book.id}}">
                          <input type="hidden" name="mod_id" id="modId" value="{{ providers.0.userID__id }}">
                        <button class="brix---btn-primary-6 w-button" >Check Out</button>
                      </div>
                    </form>
                    {% if request.user.role > 0 %}
                    <a href="{% url 'mod:editBook' book.id %}" style="color: white;"><button class="brix---btn-primary-6 w-button" style="float: right; width: 80px; text-align: center; margin-left: 3px; padding-left: 5px; padding-right: 5px;">
                      <i class="fas fa-edit"></i>
                    </button></a>
                    <a href="{% url 'mod:addCopy' book.id %}" style="color: white;"><button class="brix---btn-primary-6 w-button" style="float: right; width: 80px; text-align: center; margin-left: 3px; padding-left: 5px; padding-right: 5px;">
                      <i class="fa-solid fa-plus"></i>
                    </button></a>
                    {% endif %}
                   </div>
                </div>
              </div>
            </div>
          </div>
          <div class="divider"></div>
          <h2 class="text-500 bold mg-bottom-12px">Comments</h2>
          <div class="feedback-submission-form-block---brix w-form">
            <style>
              .rating {
                margin-top: 10px; /* Reduced space between "Rating" and stars */
                margin-bottom: 30px; /* Increased space between stars and text area */
                border: none;
                float: left;
              }
              
              .rating > label {
                color: #90A0A3;
                float: right;
              }
              
              .rating > label:before {
                margin: 5px;
                font-size: 2em;
                font-family: FontAwesome;
                content: "\f005";
                display: inline-block;
              }
              
              .rating > input {
                display: none;
              }
              
              .rating > input:checked ~ label,
              .rating:not(:checked) > label:hover,
              .rating:not(:checked) > label:hover ~ label {
                color: #F79426;
              }
              
              .rating > input:checked + label:hover,
              .rating > input:checked ~ label:hover,
              .rating > label:hover ~ input:checked ~ label,
              .rating > input:checked ~ label:hover ~ label {
                color: #FECE31;
              }
            </style>
            
            
            <form action="{% url 'home:book' book.id%}" id="wf-form-Feedback-Submission-Form-Block---Preview-Page" name="wf-form-Feedback-Submission-Form-Block---Preview-Page" data-name="Feedback Submission Form Block - Preview Page" method="post" class="feedback-submission-form---brix" data-wf-page-id="66594a63dd0674ef7467042b" data-wf-element-id="5604945f-401b-156c-35a5-b3ab59810b36">
              {% csrf_token %}
              <h3>Rating</h3>
              <div class="rating">
                <input type="radio" id="star5" name="rating" value="5" />
                <label class="star" for="star5" title="Awesome" aria-hidden="true"></label>
                <input type="radio" id="star4" name="rating" value="4" />
                <label class="star" for="star4" title="Great" aria-hidden="true"></label>
                <input type="radio" id="star3" name="rating" value="3" />
                <label class="star" for="star3" title="Very good" aria-hidden="true"></label>
                <input type="radio" id="star2" name="rating" value="2" />
                <label class="star" for="star2" title="Good" aria-hidden="true"></label>
                <input type="radio" id="star1" name="rating" value="1" />
                <label class="star" for="star1" title="Bad" aria-hidden="true"></label>
              </div>
              <br>
              <div class="text-area-div---brix">
                <br>
                <textarea placeholder="If you have any additional feedback, please type it in here..." maxlength="5000" id="Additional-Feedback-feedback-submission-form-preview" name="review" data-name="Additional Feedback" class="text-area---brix w-input" required></textarea>
              </div>
              <input type="submit" data-wait="Please wait..." class="submit-button-comment w-button" value="Comment" />
            </form>
          </div>
          <div class="divider"></div>
          <h2 class="text-500 bold mg-bottom-12px">Reviews </h2>
        </div>
      </div>
      <div class="brix---container-default-3---single-book w-container">
        <div class="sliding-box---single-book">
          <div data-delay="4000" data-animation="slide" class="brix---slider-wrapper-4 w-slider" data-autoplay="false" data-easing="ease" style="opacity: 1;" data-hide-arrows="true" data-disable-swipe="false" data-w-id="d4fa5326-9a6c-d9a9-68c9-cfe1cbacfc8c" data-autoplay-limit="0" data-nav-spacing="3" data-duration="500" data-infinite="true" role="region" aria-label="carousel">
            <div class="brix---slider-mask-width-390px w-slider-mask" id="w-slider-mask-0">
			{% if book.reviews.all %}
        {% for review in book.reviews.all reversed %}
          <div class="brix---slide-item-mg-2---5-stars w-slide" aria-label="1 of 5" role="group" aria-hidden="true" style="transform: translateX(-836px); opacity: 1; transition: transform 500ms ease 0s;">
            <div class="brix---card-testimonial-v13-2" aria-hidden="true"><img src="/static/book/template_{{review.rating}}stars.svg" alt="" class="brix---mg-bottom-24px-2" aria-hidden="true">
              <div class="brix---flex-horizontal" aria-hidden="true">
                <div aria-hidden="true">
                  <div class="brix---mg-bottom-8px-6" aria-hidden="true">
                    <div class="brix---color-neutral-830" aria-hidden="true">
                      <h3 class="brix---heading-h4-size" aria-hidden="true">
                        <a style="text-decoration: none;" href="{% url 'user:wall' review.userID.id %}">{{ review.userID }}</a>
                      </h3>
                    </div>
                  </div>
                </div>
              </div>
              <i>{{review.created_at}}</i>
              <div class="brix---mg-bottom-24px-2" aria-hidden="true">
                <div class="brix---color-neutral-829" aria-hidden="true">
                  <p class="brix---paragraph-default-13" aria-hidden="true">{{ review.review }}</p>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <p style="white-space: wrap;">There are no reviews at the moment. Be the first one to review!!!</p>
      {% endif %}
			  
      <div aria-live="polite" aria-atomic="true" class="w-slider-aria-label" data-wf-ignore="">Slide 3 of 5.</div></div>
      <div class="brix---btn-slider-arrow-left---testimonial-v12-2 w-slider-arrow-left" role="button" tabindex="0" aria-controls="w-slider-mask-0" aria-label="previous slide" style=""><img src="{% static 'book/663073a16383e5d5e16de847_left-arrow-line-icon-elements-brix-templates.svg' %}" loading="lazy" alt="Icon - Elements Webflow Library - BRIX Templates"></div>
      <div class="brix---btn-slider-arrow-right---testimonial-v12-2 w-slider-arrow-right" role="button" tabindex="0" aria-controls="w-slider-mask-0" aria-label="next slide"><img src="{% static 'book/663073a16383e5d5e16de8d9_right-arrow-line-icon-elements-brix-templates.svg' %}" loading="lazy" alt="Icon - Elements Webflow Library - BRIX Templates"></div>
      <div class="brix---hidden-desktop w-slider-nav w-round"><div class="w-slider-dot" data-wf-ignore="" aria-label="Show slide 1 of 5" aria-pressed="false" role="button" tabindex="-1" style="margin-left: 3px; margin-right: 3px;"></div><div class="w-slider-dot" data-wf-ignore="" aria-label="Show slide 2 of 5" aria-pressed="false" role="button" tabindex="-1" style="margin-left: 3px; margin-right: 3px;"></div><div class="w-slider-dot w-active" data-wf-ignore="" aria-label="Show slide 3 of 5" aria-pressed="true" role="button" tabindex="0" style="margin-left: 3px; margin-right: 3px;"></div><div class="w-slider-dot" data-wf-ignore="" aria-label="Show slide 4 of 5" aria-pressed="false" role="button" tabindex="-1" style="margin-left: 3px; margin-right: 3px;"></div><div class="w-slider-dot" data-wf-ignore="" aria-label="Show slide 5 of 5" aria-pressed="false" role="button" tabindex="-1" style="margin-left: 3px; margin-right: 3px;"></div></div>
          </div>
        </div>
      </div>
{% endblock %}

templates/home/checkoutResult.html
{% extends 'base/base.html' %}

{% block content %}
{% load static %}
{% include 'base/message.html' %}


<link href="{% static 'result/webflow-style.css' %}"  rel="stylesheet" type="text/css" />



<div class="dashboard-content utility-page-content">
    <div class="dashboard-main-content utility-page-main-content">
      <div class="block-thank-you">
        <div class="container-default---thank-you w-container">
          <div class="card---thank-you amount-over-graph---thank-you">
            <div class="title-container---brix---checkout">
              <h2 class="heading-2---checkout">Thank you for your borrowing!</h2>
              <div class="brix---mg-bottom-16px-11---thank-you"><a href="#" class="brix---avatar-circle-8 w-inline-block"><img src="{% static 'result/thank-20you.svg' %}" alt="" class="brix---avatar-image-link-3" /></a></div>
            </div>
            <div class="inner-container _326px center">
              <p class="mg-bottom-24px---thank-you">We will notify you by email when your borrow request is accepted by a provider!</p>
            </div>
            <div class="flex-horizontal"><a data-w-id="dc3b625c-4a68-4ebe-9b74-d3193fa9f32f" href="{% url 'home:gallery' %}" class="btn-primary w-inline-block">
                <div class="flex-horizontal gap-column-4px">
                  <div>Back to home</div>
                </div>
              </a></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% endblock %}

templates/home/panel.html
<div class="bookContainer">
  <div class="leftColumn">
    <a href="{% url 'home:book' item.id %}">
      {% include 'base/bookCover.html' %}
    </a>
  </div>
  <div class="rightColumn p-2">
    <p>
      ID: {{item.id}}
      <span class="float-right m-1"><a href="#extension_{{item.id}}" data-toggle="collapse" aria-controls="extension_{{item.id}}">
        <i class="fa-solid fa-bars"></i>
      </a></span>
      <span class="badge badge-success float-right m-1">{{ item.language }}</span>
      <span class="badge badge-warning float-right m-1">{{ item.get_type_display }}</span>
      {% if item.pdfFile %}
      <span class="badge badge-info float-right m-1">E-book</span>
      {% endif %}
    </p>
    <h5><a href="{% url 'home:book' item.id%}">{{item.title}}</a></h5>
    <p>{{item.author}}</p>
    {% if item.publisher and item.publication %}
    <p>{{item.publisher}}@{{item.publication}}</p>
    {% else %}
      {% if item.publisher %}
      <p>{{item.publisher}}</p>
      {% else %}
      <p>{{item.publication}}</p>
      {% endif %}
    {% endif %}
    <div class="collapse" id="extension_{{item.id}}">
      {% if request.user.is_authenticated and request.user.role >= 1 %}
      <a class="btn btn-primary" href="{% url 'mod:addCopy' item.id %}">Add Copy</a>
      <a class="btn btn-primary" href="{% url 'mod:editBook' item.id %}">Edit Book</a>
      {% endif %}
      <a class="btn btn-primary" href="{% url 'home:book' item.id%}">Detail</a>
      <p>
        {{ item.description }}
      </p>
    </div>
  </div>

</div>

templates/home/shelfItem.html
<div class="shelfItemContainer">
  <div class="bookContainer">
    <div class="leftColumn">
      <a href="{% url 'home:book' item.0.bookID.id %}">
        {% if item.0.bookID.coverImage %}
        <img  src="/media/{{ item.0.bookID.coverImage }}" 
        width="80px" height="100px" alt="image" style="object-fit: cover;">
        {% else %}
        <img class="rounded-circle" src="/media/book/defaultCover.png" width="150px" alt="image">
        {% endif %}
      </a>
    </div>
    <div class="rightColumn p-2">
      <p>
        ID: {{item.0.bookID.id}}
        <span class="float-right m-1">
          <a href="#extension_{{item.0.bookID.id}}" data-toggle="collapse" aria-controls="extension_{{item.0.bookID.id}}">
          Show {{item.count}} copies <i class="fa-solid fa-bars"></i>
          </a>
        </span>
        <span class="badge badge-success float-right m-1">{{ item.0.bookID.language }}</span>
        <span class="badge badge-warning float-right m-1">{{ item.0.bookID.get_type_display }}</span>
        {% if item.0.bookID.pdfFile %}
        <span class="badge badge-info float-right m-1">E-book</span>
        {% endif %}
      </p>
      <h5><a href="{% url 'home:book' item.0.bookID.id%}">{{item.0.bookID.title}}</a></h5>
      <p>{{item.0.bookID.author}}
      <span style="float: right">
      {% if item.0.bookID.publisher and item.0.bookID.publication %}
        {{item.0.bookID.publisher}}@{{item.0.bookID.publication}}
      {% else %}
        {% if item.0.bookID.publisher %}
          {{item.0.bookID.publisher}}
        {% else %}
          {{item.0.bookID.publication}}
        {% endif %}
      {% endif %}
      </span>
      </p>
    </div>
  </div>
  <div class="collapse" id="extension_{{item.0.bookID.id}}" style="width: 100%;">
    {% for copy in item %}
      <div class="copyContainer">
        <p>
          {% if copy.userID == request.user %}
          <span class="float-right"><a href="{% url 'mod:editCopy' copy.id %}">Edit Copy</a></span>
          {% endif %}
          <span class="badge badge-success float-left">{{ copy.get_status_display }}</span>
          <i class="m-3">Copy ID: {{ copy.id }}</i>
        </p>
        <p>
          {{copy.note}}
        </p>
      </div>
    {% endfor %}
  </div>
</div>