Bibliotech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Pages for everyone (even guests)
    path('', include('home.urls')),

    # User pages
    path('user/', include('user.urls')),

    # For login using all-auth (OAuth2)
    path('accounts/', include('socialplatform.urls')),

    # Moderator pages
    path('mod/', include('moderator.urls')),

    # Admin (Control) pages
    path('control/', include('control.urls')),

    # Default django admin page
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    
handler404 = 'home.views.handling_404'

home/urls.py
from django.contrib import admin
from django.urls import path,include
from home.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'
urlpatterns = [
    path('', indexView.as_view(), name='index'),
    path('dashboard', dashboardView.as_view(), name="dashboard"),
    path("gallery", galleryView.as_view(), name="gallery"),
    path('gallery/bookid=<int:id>/detail',bookView.as_view(), name="book"),
    path('gallery/bookid=<int:id>/pdf', bookPDFView.as_view(), name="bookPDF"),
    path('shelf/userid=<int:id>',shelfView.as_view(), name = "shelf"),
    path('borrow/bookid=<int:id>',borrowView.as_view(), name = "borrow"),
    path('faq', faqView.as_view(), name='faq'),
    path('contact', contactView.as_view(), name='contact'),
    path('result', resultView.as_view(), name='result'),
]

user/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, reverse_lazy
from user.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'
urlpatterns = [
    path('register/', registerView.as_view(), name="register"),
    path('login/', loginView.as_view(), name='login'),
    path('logout/', logoutView.as_view(), name='logout'),
    path("password", changePasswordView.as_view(), name="changePassword"),

    path("recover", recoverAccountView.as_view(), name="recover"),
    path("recover/sent", recoverDoneView.as_view(), name="recover_done"),
    path("recover/<uidb64>/<token>", recoverConfirmView.as_view(), name="recover_confirm"),
    path("recover/complete", recoverCompleteView.as_view(), name="recover_complete"),

    path("profile/info/", profileInfoRedirectView.as_view(), name="info"),
    path("profile/userID=<int:id>/", profileInfoView.as_view(), name="wall"),
    path("profile/borrow/", userBorrowanceManagerView.as_view(), name="borrow"),
    path("profile/edit/", profileEditView.as_view(), name="edit"),
    path("activate/<uidb64>/<token>", activate, name="activate"),
]

if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

# Create your models here.
def getBookImageURL(instance, filename):
  if instance.id != None:
      return "book/{}/coverImage.png".format(instance.id)
  else:
    queryset = Book.objects.all().order_by('pk')
    last = queryset.last()
    last_id = last.id
    file_number = last_id+1
    return "book/{}/coverImage.png".format(file_number)

def getBookPDFURL(instance, filename):
  if instance.id != None:
      return "book/{}/pdfFile.pdf".format(instance.id)
  else:
    queryset = Book.objects.all().order_by('pk')
    last = queryset.last()
    last_id = last.id
    file_number = last_id+1
    return "book/{}/pdfFile.pdf".format(file_number)

def getUserImageURL(instance, filename):
  if instance.id != None:
      return "user/{}/avatar.png".format(instance.id)
  else:
    queryset = User.objects.all().order_by('pk')
    last = queryset.last()
    last_id = last.id
    file_number = last_id+1
    return "user/{}/avatar.png".format(file_number)

class User(AbstractUser):
  email = models.EmailField(null=False, blank=False, unique=True, help_text="Required", error_messages="This field is compulsory and must follow email format")
  avatar = models.ImageField(upload_to=getUserImageURL, null=True, blank=True)
  birthdate = models.DateField(null=True, blank=True)
  genderChoices = (
    (0, "male"),
    (1, "female"),
    (2, "other")
  )
  gender = models.IntegerField(choices=genderChoices, null=False, default=2)
  address = models.CharField(max_length=200, null=True, blank=True)
  phoneNum = models.CharField(max_length=50, null=True, blank=True)
  roleChoices = (
    (0, "user"),
    (1, "moderator"),
    (2, "admin"),
    (3, "banned")
  )
  role = models.IntegerField(choices=roleChoices, default=0)
  description = models.CharField(max_length=1500, null=True, blank=True)
  availableWorkingHours = models.CharField(max_length=300, null=True, blank=True)

class Book(models.Model):
  title = models.CharField(max_length=200, null=False, default="UNTITLED")
  author = models.CharField(max_length=200, null=False, default="UNKNOWN")
  typeChoices = (
    (0, "article"),
    (1, "book"),
    (2, "magazine"),
    (3, "video/audio"),
    (4, "comic"),
    (5, "other")
  )
  type = models.IntegerField(choices=typeChoices, null=True, default=0)
  liteCate = models.BooleanField(default=False, blank=True, null=True)
  socieCate = models.BooleanField(default=False, blank=True, null=True)
  naturCate = models.BooleanField(default=False, blank=True, null=True)
  techCate = models.BooleanField(default=False, blank=True, null=True)
  poliCate = models.BooleanField(default=False, blank=True, null=True)
  romanCate = models.BooleanField(default=False, blank=True, null=True)
  enterCate = models.BooleanField(default=False, blank=True, null=True)
  otherCate = models.BooleanField(default=False, blank=True, null=True)
  language = models.CharField(max_length=200, null=True, blank=True)
  description = models.TextField(max_length=1500, null=True, blank=True)
  coverImage = models.ImageField(upload_to=getBookImageURL, null=True, blank=True)
  pdfFile = models.FileField(upload_to=getBookPDFURL,null=True,blank=True)
  publisher = models.CharField(max_length=200, null=True, blank=True)
  publication = models.CharField(max_length=50, null=True, blank=True)
  codeISBN = models.CharField(max_length=50, null=True, blank=True)
  statusChoices = (
    (0, "pending"),
    (1, "accepted"),
    (2, "rejected")
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=True)
  id = models.AutoField(primary_key=True)
  manual = models.BooleanField(default=True, null = True, blank = True)

  def __str__(self) :
    return str(self.id) + ". " + self.title


class Copy(models.Model):
  bookID = models.ForeignKey(Book, null=False, on_delete=models.CASCADE)
  userID = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
  statusChoices = (
    (0, "hidden"),
    (1, "available"),
    (2, "borrowed"),
    (3, "unavailable")
  )
  status = models.IntegerField(choices=statusChoices, default=0)
  note = models.TextField(max_length=200, null=True, blank=True)
  regDate = models.DateTimeField(null=False)

  def __str__(self) :
    return str(self.id) + ". " + self.bookID.title


class Borrowance(models.Model):
  copyID = models.ForeignKey(Copy, on_delete=models.CASCADE)
  userID = models.ForeignKey(User, on_delete=models.CASCADE)
  borrowDate = models.DateTimeField(null=False)
  expiredDate = models.DateTimeField(null=False)
  statusChoices = (
    (0, "request"),
    (1, "double-check"),
    (2, "borrowing"),
    (3, "returned"),
    (4, "overdue"),
    (5, "lost")
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=False)
  deposit = models.FloatField(default=0, null=True, blank=True)


class Review(models.Model):
  bookID = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='reviews')
  userID = models.ForeignKey(User, on_delete=models.CASCADE)

  def validateRating(value):
    if (value > 5 or value < 1):
      raise ValidationError(
        _('%(value)s is not valid'),
        params={'value': value},
      )
    
  rating = models.IntegerField(validators=[validateRating], null=True, blank=True)
  review = models.TextField(max_length=1500, null=True, blank=True)
  created_at = models.DateTimeField(default=timezone.now)

  def __str__(self) :
    return "Review " + str(self.id)
  
def getApplicantDocURL(instance, filename):
  return "user/{}/modApplication.pdf".format(instance.applicant.id)

class ModApplication(models.Model):
  applicant = models.ForeignKey(User, on_delete=models.CASCADE)
  applicantDocument = models.FileField(upload_to=getApplicantDocURL,null=True,blank=True)
  applicantText = models.TextField(max_length=1500, null=True, blank=True)
  adminComment = models.TextField(max_length=1500, null=True, blank=True)
  statusChoices = (
    (0, "applying"),
    (1, "approved"),
    (2, "denied"),
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=False)
  created_at = models.DateTimeField(default=timezone.now)
  
class Thought(models.Model):
  userID = models.ForeignKey(User, on_delete=models.CASCADE)
  thought = models.TextField(max_length=1500, null=False)
  created_at = models.DateTimeField(default=timezone.now)
  
class BookApplication(models.Model):
  bookID = models.ForeignKey(Book, on_delete=models.CASCADE)
  uploader = models.ForeignKey(User, on_delete=models.CASCADE)
  statusChoices = (
    (0, "applying"),
    (1, "approved"),
    (2, "denied"),
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=False)
  created_at = models.DateTimeField(default=timezone.now)

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ValidationError

from home.models import Thought, User


class LoginForm(AuthenticationForm):
  class Meta:
    model = User
    fields = "__all__"


class RegisterForm(UserCreationForm):
  class Meta:
    model = User
    fields = ["username", "email", "password1", "password2",
              "first_name", "last_name", "birthdate", "gender",
              "address", "phoneNum"]
    # fields = "__all__"

  def clean(self):
    email = self.cleaned_data.get('email')
    if User.objects.filter(email=email).exists():
        raise ValidationError("Email exists")
    return self.cleaned_data

class ProfileEditForm(forms.ModelForm):

  class Meta:
    model = User
    fields = ["avatar", "first_name", "last_name", "birthdate", "gender",
              "address", "phoneNum"]
    
class ThoughtForm(forms.ModelForm):
  class Meta:
    model = Thought
    fields = "__all__"

templates/user/recover/recoverComplete.html
{% extends 'base/base.html' %}

{% load static %}
{% include 'base/message.html' %}
{% load i18n %}

{% block title %}{% trans "Password reset complete" %}{% endblock %}

{% block content %}
<div class="container">
    <p>
        {% trans "Your password has been reset!" %}
        <a href="{% url 'user:login' %}">{% blocktrans %}You may now log in{% endblocktrans %}.</a>
    </p>
</div>
{% endblock %}

templates/user/recover/recoverConfirm.html
{% extends 'base/base.html' %}

{% load static %}
{% include 'base/message.html' %}
{% load i18n %}

{% block meta %}
<!-- NOTE(joshblum): This prevents leaking the password reset token via the
   Referer header to any 3rd party apps on the page. -->
<meta name="referrer" content="origin">
{% endblock %}

{% block title %}{% trans "Confirm password reset" %}{% endblock %}

{% block content %}
  {% if validlink %}
<style>
  .input-valid {
    border: 2px solid green;
  }
  .input-invalid {
    border: 2px solid red;
  }
  .condition-valid {
    color: green;
  }
  .condition-invalid {
    color: red;
  }
  .disabled-button {
    background-color: grey !important;
    cursor: not-allowed !important;
  }
</style>
<div style="opacity: 1;" class="page-wrapper">
  <div class="w-nav-overlay" data-wf-ignore="" id="w-nav-overlay-0"></div>
</div>
<div class="main-section">
  <div class="container-default w-container">
    <div class="block-sticky-top---main-contain">
      <div id="w-node-_5b7b5ab1-6d00-c7e0-62e6-f29490555c22-71edfef9" class="dashboard-main-content---user-profiles">
        <div id="cards" data-w-id="c25945b2-b467-1640-757f-35242a0cbdb5" style="opacity: 1;" class="pd-top-24px---activities">
          <h2 class="text-500 bold mg-bottom-12px">Change Password</h2>
          <div class="card component-card card-one-line">
            <div class="w-form">
              
              <form action="{% url 'user:recover_confirm' uidb64=uidb64 token=token %}" id="wf-form-signup" name="wf-form-signup" method="post" class="container_profile-form-2" aria-label="signup">
                {% csrf_token %}
                <div class="spacer_m"></div>
                <div>Use this form to reset your password.</div>
                <div class="spacer_m"></div>
                
                <div class="input-wrapper">
                  <label for="new_password1" class="input-label">New password</label>
                  <input class="input-2 w-input" maxlength="256" name="new_password1" placeholder="" type="text" id="new_password1" required />
                </div>
                <div class="input-wrapper">
                  <label for="new_password2" class="input-label">Repeat new password</label>
                  <input class="input-2 w-input" maxlength="256" name="new_password2" placeholder="" type="text" id="new_password2" required />
                </div>
                <div class="description">
                  <em>
                    * Your password: <br />
                    <span id="lengthP" class="condition-invalid">&nbsp;&nbsp;&nbsp;&nbsp;has at least 8 characters.</span><br />
                    <span id="valid-charsP" class="condition-invalid">&nbsp;&nbsp;&nbsp;&nbsp;has a combination of letters, numbers, and symbols.</span><br/>
                    <span id="matchP" class="condition-invalid">&nbsp;&nbsp;&nbsp;&nbsp;matches the confirmation password.</span>
                  </em>
                </div>
                <div class="spacer_m"></div>
                <div class="block-button">
                  <input type="submit" class="log-in-button---brix w-button disabled-button" id="change-password-button" value="Change Password" disabled>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  var lengthOK = false;
  var wordRegexOK = false;
  var confirmation = false;

  function checkChangePasswordButton() {
      const changePasswordButton = document.getElementById('change-password-button');
      if (lengthOK && wordRegexOK && confirmation) {
          changePasswordButton.disabled = false;
          changePasswordButton.classList.remove('disabled-button');
      } else {
          changePasswordButton.disabled = true;
          changePasswordButton.classList.add('disabled-button');
      }
  }

  document.getElementById('new_password1').addEventListener('input', function () {
      const passwordInput = this.value;
      const lengthP = document.getElementById('lengthP');
      const validCharsP = document.getElementById('valid-charsP');

      // Check length
      if (passwordInput.length >= 8) {
          lengthP.classList.remove('condition-invalid');
          lengthP.classList.add('condition-valid');
          lengthOK = true;
      } else {
          lengthP.classList.remove('condition-valid');
          lengthP.classList.add('condition-invalid');
          lengthOK = false;
      }

      // Check for valid characters
      const regex = /^(?=.*[a-zA-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]+$/;
      if (regex.test(passwordInput)) {
          validCharsP.classList.remove('condition-invalid');
          validCharsP.classList.add('condition-valid');
          wordRegexOK = true;
      } else {
          validCharsP.classList.remove('condition-valid');
          validCharsP.classList.add('condition-invalid');
          wordRegexOK = false;
      }

      checkChangePasswordButton();
  });

  document.getElementById('new_password2').addEventListener('input', function () {
      const passwordInput = document.getElementById('new_password1').value;
      const confirmationInput = this.value;
      const matchP = document.getElementById('matchP');

      // Check if passwords match
      if (passwordInput === confirmationInput) {
          matchP.classList.remove('condition-invalid');
          matchP.classList.add('condition-valid');
          confirmation = true;
      } else {
          matchP.classList.remove('condition-valid');
          matchP.classList.add('condition-invalid');
          confirmation = false;
      }

      checkChangePasswordButton();
  });
</script>
{% comment %} <div class="container">
  {% if validlink %}
    <p>{% trans "Enter your new password below to reset your password:" %}</p>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Set password' %}" />
    </form>
  {% else %}
    Password reset unsuccessful. Please try again or contact an administrator.</a>
  {% endif %}
</div> {% endcomment %}
  {% else %}
  <div class="dashboard-content utility-page-content">
    <div class="dashboard-main-content utility-page-main-content">
      
        <div class="container-default w-container">
          <div data-w-id="619efe17469a19c94a600b1500000000000b" style="transform: translate3d(0px, 0%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); opacity: 1; transform-style: preserve-3d;" class="utility-page-content mg-bottom-0 w-form">
            <div class="card _404"><img src="{% static 'user/recovery/404.svg' %}" loading="lazy" alt="" class="_404">
              <h2 class="text-500 bold color-neutral-800">Oops! Page not found</h2>
              <div class="inner-container _326px center">
                <p class="mg-bottom-24px">The page you are looking for doesn't exist or has been moved</p>
              </div>
              <div class="flex-horizontal"><a data-w-id="dc3b625c-4a68-4ebe-9b74-d3193fa9f32f" href="{% url 'home:index' %}" class="btn-primary w-inline-block">
                  <div class="flex-horizontal gap-column-4px">
                    <div>Back to home</div>
                  </div>
                </a></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/user/recover/recoverDone.html
{% extends 'base/base.html' %}

{% load static %}
{% include 'base/message.html' %}
{% load i18n %}

{% block title %}{% trans "Password reset" %}{% endblock %}

{% block content %}
<div class="container">
    <p>
        {% blocktrans %}
        We have sent you an email with a link to reset your password. Please check
        your email and click the link to continue.
        {% endblocktrans %}
    </p>
</div>
{% endblock %}

templates/user/recover/recoverEmail.html
{% load i18n %}
{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://vgupe2024team2clone-production.up.railway.app{% url 'user:recover_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The BiblioTech team{% endblocktranslate %}

{% endautoescape %}

templates/user/recover/recoverForm.html
{% extends 'base/base.html' %}

{% load static %}

{% load i18n %}

{% block title %}{% trans "Reset password" %}{% endblock %}

{% block content %}

{% comment %} {% include 'base/message.html' %} {% endcomment %}
{% include 'base/message.html' %}
<div class="w-nav-overlay" data-wf-ignore="" id="w-nav-overlay-0"></div> 
          <div class="container-default---login w-container">
            <div data-w-id="bffbe75b-d95c-3992-bdd3-befc9d0bd453" style="opacity: 1;" class="mg-bottom-48px---login">
              <div class="sign-in-form-block---brix w-form">

                <form action="{% url 'user:recover' %}" id="wf-form-Sign-in-V1" name="wf-form-Sign-in-V1" data-name="Sign in V1" method="post" class="sign-in-form-v1---brix" data-wf-page-id="6631019727c76c1f85d4a18f" data-wf-element-id="07381e2a-d17a-38e9-de5c-b7fc4244450c" aria-label="Sign in V1">
                  {% csrf_token %} 
                   <div class="title-container---brix">
                    <h2 class="heading-2---sign-in">{% trans "Forgot Password" %}</h2>
                    <p class="paragraph-52">{% trans "Please fill your email to reset your password" %}</p>
                  </div>
                  <div class="input-div---brix">
                    <input class="input---brix name-icon---brix w-input" maxlength="256" name="email" data-name="Email" placeholder="youremail@gmail.com" type="email" id="id_email" required="">
                  </div>
                  <input type="submit" data-wait="Please wait..." class="log-in-button---brix w-button" value="{% trans 'Reset password' %}">
                </form>       

              </div>
            </div>
          </div>
     

{% endblock %}


{# This is used by django.contrib.auth #}



{% comment %} <div class="container">
  <h4>Account Recover View</h4>
  <p>
      {% blocktrans %}
      Forgot your password? Enter your email in the form below and we'll send you instructions for creating a new one.
      {% endblocktrans %}
  </p>
  <form method="post" action="">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="{% trans 'Reset password' %}" />
  </form>
</div> {% endcomment %}