Bibliotech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Pages for everyone (even guests)
    path('', include('home.urls')),

    # User pages
    path('user/', include('user.urls')),

    # For login using all-auth (OAuth2)
    path('accounts/', include('socialplatform.urls')),

    # Moderator pages
    path('mod/', include('moderator.urls')),

    # Admin (Control) pages
    path('control/', include('control.urls')),

    # Default django admin page
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    
handler404 = 'home.views.handling_404'

home/urls.py
from django.contrib import admin
from django.urls import path,include
from home.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'
urlpatterns = [
    path('', indexView.as_view(), name='index'),
    path('dashboard', dashboardView.as_view(), name="dashboard"),
    path("gallery", galleryView.as_view(), name="gallery"),
    path('gallery/bookid=<int:id>/detail',bookView.as_view(), name="book"),
    path('gallery/bookid=<int:id>/pdf', bookPDFView.as_view(), name="bookPDF"),
    path('shelf/userid=<int:id>',shelfView.as_view(), name = "shelf"),
    path('borrow/bookid=<int:id>',borrowView.as_view(), name = "borrow"),
    path('faq', faqView.as_view(), name='faq'),
    path('contact', contactView.as_view(), name='contact'),
    path('result', resultView.as_view(), name='result'),
]

moderator/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "mod"
urlpatterns = [
    path("", modView.as_view(), name='mod'),
    path("addBook", addBookView.as_view(), name='addBook'),
    path('editBook/bookid=<int:id>', editBookView.as_view(), name='editBook'),
    path('addCopy/bookid=<int:id>', addCopyView.as_view(), name='addCopy'),
    path('editCopy/copyid=<int:id>', editCopyView.as_view(), name="editCopy"),
    path('apply', applyModView.as_view(), name="modApply"),
    path('modManage',modManageView.as_view(), name="modManage_get"),
    path('modManage/<int:id>',modManageView.as_view(), name="modManage_post"),
    path('adminManage',adminManageView.as_view(), name="adminManage"),
    path('adminManage/<int:id>',adminManageView.as_view(), name="adminManage_post"),
    path('deleteBook/bookid=<int:id>',deleteBook,name='deleteBook'),
    # Do not uncomment "import"
    # This function is only used to automatically add book
    # path('import', importDataView.as_view(), name="import"),
]




if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

# Create your models here.
def getBookImageURL(instance, filename):
  if instance.id != None:
      return "book/{}/coverImage.png".format(instance.id)
  else:
    queryset = Book.objects.all().order_by('pk')
    last = queryset.last()
    last_id = last.id
    file_number = last_id+1
    return "book/{}/coverImage.png".format(file_number)

def getBookPDFURL(instance, filename):
  if instance.id != None:
      return "book/{}/pdfFile.pdf".format(instance.id)
  else:
    queryset = Book.objects.all().order_by('pk')
    last = queryset.last()
    last_id = last.id
    file_number = last_id+1
    return "book/{}/pdfFile.pdf".format(file_number)

def getUserImageURL(instance, filename):
  if instance.id != None:
      return "user/{}/avatar.png".format(instance.id)
  else:
    queryset = User.objects.all().order_by('pk')
    last = queryset.last()
    last_id = last.id
    file_number = last_id+1
    return "user/{}/avatar.png".format(file_number)

class User(AbstractUser):
  email = models.EmailField(null=False, blank=False, unique=True, help_text="Required", error_messages="This field is compulsory and must follow email format")
  avatar = models.ImageField(upload_to=getUserImageURL, null=True, blank=True)
  birthdate = models.DateField(null=True, blank=True)
  genderChoices = (
    (0, "male"),
    (1, "female"),
    (2, "other")
  )
  gender = models.IntegerField(choices=genderChoices, null=False, default=2)
  address = models.CharField(max_length=200, null=True, blank=True)
  phoneNum = models.CharField(max_length=50, null=True, blank=True)
  roleChoices = (
    (0, "user"),
    (1, "moderator"),
    (2, "admin"),
    (3, "banned")
  )
  role = models.IntegerField(choices=roleChoices, default=0)
  description = models.CharField(max_length=1500, null=True, blank=True)
  availableWorkingHours = models.CharField(max_length=300, null=True, blank=True)

class Book(models.Model):
  title = models.CharField(max_length=200, null=False, default="UNTITLED")
  author = models.CharField(max_length=200, null=False, default="UNKNOWN")
  typeChoices = (
    (0, "article"),
    (1, "book"),
    (2, "magazine"),
    (3, "video/audio"),
    (4, "comic"),
    (5, "other")
  )
  type = models.IntegerField(choices=typeChoices, null=True, default=0)
  liteCate = models.BooleanField(default=False, blank=True, null=True)
  socieCate = models.BooleanField(default=False, blank=True, null=True)
  naturCate = models.BooleanField(default=False, blank=True, null=True)
  techCate = models.BooleanField(default=False, blank=True, null=True)
  poliCate = models.BooleanField(default=False, blank=True, null=True)
  romanCate = models.BooleanField(default=False, blank=True, null=True)
  enterCate = models.BooleanField(default=False, blank=True, null=True)
  otherCate = models.BooleanField(default=False, blank=True, null=True)
  language = models.CharField(max_length=200, null=True, blank=True)
  description = models.TextField(max_length=1500, null=True, blank=True)
  coverImage = models.ImageField(upload_to=getBookImageURL, null=True, blank=True)
  pdfFile = models.FileField(upload_to=getBookPDFURL,null=True,blank=True)
  publisher = models.CharField(max_length=200, null=True, blank=True)
  publication = models.CharField(max_length=50, null=True, blank=True)
  codeISBN = models.CharField(max_length=50, null=True, blank=True)
  statusChoices = (
    (0, "pending"),
    (1, "accepted"),
    (2, "rejected")
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=True)
  id = models.AutoField(primary_key=True)
  manual = models.BooleanField(default=True, null = True, blank = True)

  def __str__(self) :
    return str(self.id) + ". " + self.title


class Copy(models.Model):
  bookID = models.ForeignKey(Book, null=False, on_delete=models.CASCADE)
  userID = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
  statusChoices = (
    (0, "hidden"),
    (1, "available"),
    (2, "borrowed"),
    (3, "unavailable")
  )
  status = models.IntegerField(choices=statusChoices, default=0)
  note = models.TextField(max_length=200, null=True, blank=True)
  regDate = models.DateTimeField(null=False)

  def __str__(self) :
    return str(self.id) + ". " + self.bookID.title


class Borrowance(models.Model):
  copyID = models.ForeignKey(Copy, on_delete=models.CASCADE)
  userID = models.ForeignKey(User, on_delete=models.CASCADE)
  borrowDate = models.DateTimeField(null=False)
  expiredDate = models.DateTimeField(null=False)
  statusChoices = (
    (0, "request"),
    (1, "double-check"),
    (2, "borrowing"),
    (3, "returned"),
    (4, "overdue"),
    (5, "lost")
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=False)
  deposit = models.FloatField(default=0, null=True, blank=True)


class Review(models.Model):
  bookID = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='reviews')
  userID = models.ForeignKey(User, on_delete=models.CASCADE)

  def validateRating(value):
    if (value > 5 or value < 1):
      raise ValidationError(
        _('%(value)s is not valid'),
        params={'value': value},
      )
    
  rating = models.IntegerField(validators=[validateRating], null=True, blank=True)
  review = models.TextField(max_length=1500, null=True, blank=True)
  created_at = models.DateTimeField(default=timezone.now)

  def __str__(self) :
    return "Review " + str(self.id)
  
def getApplicantDocURL(instance, filename):
  return "user/{}/modApplication.pdf".format(instance.applicant.id)

class ModApplication(models.Model):
  applicant = models.ForeignKey(User, on_delete=models.CASCADE)
  applicantDocument = models.FileField(upload_to=getApplicantDocURL,null=True,blank=True)
  applicantText = models.TextField(max_length=1500, null=True, blank=True)
  adminComment = models.TextField(max_length=1500, null=True, blank=True)
  statusChoices = (
    (0, "applying"),
    (1, "approved"),
    (2, "denied"),
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=False)
  created_at = models.DateTimeField(default=timezone.now)
  
class Thought(models.Model):
  userID = models.ForeignKey(User, on_delete=models.CASCADE)
  thought = models.TextField(max_length=1500, null=False)
  created_at = models.DateTimeField(default=timezone.now)
  
class BookApplication(models.Model):
  bookID = models.ForeignKey(Book, on_delete=models.CASCADE)
  uploader = models.ForeignKey(User, on_delete=models.CASCADE)
  statusChoices = (
    (0, "applying"),
    (1, "approved"),
    (2, "denied"),
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=False)
  created_at = models.DateTimeField(default=timezone.now)

templates/mod/addCopy.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
{% include 'base/message.html' %}

{% if form.errors %}
    {% for field in form %}
    {{field}}
        {% for error in field.errors %}
            <p> {{ error }} </p>
        {% endfor %}
    {% endfor %}
{% endif %}

<div class="main-section" style="padding-top: 3vw;">
  <div class="container-default w-container">
    <div class="block-sticky-top---main-contain">
      <div id="w-node-_5b7b5ab1-6d00-c7e0-62e6-f29490555c22-9a24b53f" class="dashboard-main-content---user-profiles">
        <div id="cards" class="pd-top-24px---activities">

          <div class="card component-card card-one-line" style="max-width: 95vw;">
            <div class="w-form">


              <style>
                .w-checkbox-input--inputType-custom.w--redirected-checked {
                    background-color: #3898ec;
                    background-image: url("{% static 'gallery/custom-checkbox-checkmark.589d534424.svg' %}");
                    background-position: 50%;
                    background-repeat: no-repeat;
                    background-size: cover;
                    border-color: #3898ec;
                }
              </style>


<form id="wf-form-signup" name="wf-form-signup" data-name="signup" method="post" action="{% url 'mod:addCopy' book.id %}" data-ms-form="profile" class="container_profile-form-2" data-wf-page-id="66304d01b2d8ae4b9a24b53f" data-wf-element-id="42ebedb0-94f6-ae4e-e956-e07ffc90504a">
  {% csrf_token %}
  <h1 class="h1_small">Add Copy</h1>
  <div>Use the form below to add your copy of the book to your bookshelf. </div>
  <div class="spacer_m"></div>
  <div class="row">
    <div class="column" style="width: 60%; display: inline-block; padding: auto;">
      <div class="input-wrapper _15p-right" style="padding-top: 4vw;"><label for="First-Name-4" class="input-label">Title</label><h3 style="padding-left: 20px; padding-top: 10px;">{{book.title}}</h3></div>
      <div class="input-wrapper"><label for="Author" class="input-label">Author</label><h4 style="padding-left: 20px; padding-top: 10px;">{{book.author}}</h4></div>
    </div>
    <div class="column" style="width: 30%; float: right; padding-right: 5%;">

      {% if book.coverImage %}          
        {% if book.manual == True  %} 
        <img src="{{ book.coverImage.url }}" alt="" style="width: 100%; float: right;" />
    
        {% else %}   
        <img src="{{ book.coverImage }}" alt="" style="width: 100%; float: right;" />
    
        {% endif %}                 
      {% else %}   
      <img src="/media/book/defaultCover.jpg" alt="" style="width: 100%40vw; float: right;" />         
    
      {% endif %}  
    </div>
  </div>
  <div class="spacer_xs"></div>
  <textarea class="input-2 w-input" name="note" id="note" placeholder="Write your note for this copy here."></textarea>
  
  <div class="padding-button-block" style="margin-top: 30px;">
    <div class="submit-button-book"><input type="submit" data-wait="Please wait..." class="btn-primary---save w-button" value="Submit" /></div>
  </div>
</form>
              
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/mod/editCopy.html
{% extends 'base/base.html' %}


{% block content %}
{% load static %}
{% include 'base/message.html' %}
{% comment %}
<div class="w-layout-grid brix---grid-3-columns-3">
<div class="container">
  <h3>Edit Copy View</h3> 
  <br>
  <h4>{{copy.bookID.title}}</h4>
  <p>{{copy.bookID.author}}</p>
  <p>{{copy.bookID.codeISBN}}</p>
  <hr class="hr" />
  <p>Copy ID: {{copy.id}}</p>
  <p>Owner: {{copy.userID.last_name}}, {{copy.userID.first_name}}</p>
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edit">
  </form>
</div>
</div>
{% endcomment %}
<div class="main-section">
  <div class="container-default w-container">
    <div class="block-sticky-top---main-contain">
      <div id="w-node-_5b7b5ab1-6d00-c7e0-62e6-f29490555c22-9a24b53f" class="dashboard-main-content---user-profiles">
        <div id="cards" class="pd-top-24px---activities">
          <div class="card component-card card-one-line">
            <div class="w-form">


              <form action="{% url 'mod:editCopy' copy.id%}" id="wf-form-signup" name="wf-form-signup" data-name="signup" method="post" enctype="multipart/form-data" data-ms-form="profile" class="container_profile-form-2" data-wf-page-id="66304d01b2d8ae4b9a24b53f" data-wf-element-id="42ebedb0-94f6-ae4e-e956-e07ffc90504a">
                {% csrf_token %}
                <h1 class="h1_small">Edit copy of {{copy.bookID.title}}</h1>
                <div class="spacer_xs"></div>
                <div>Use the form below to edit copy of {{copy.bookID.title}}. </div>
                <div class="spacer_m"></div>             
                <div class="input-wrapper"><label for="Author" class="input-label">Note</label><input class="input-2 w-input" maxlength="256" name="note" data-name="Author" placeholder="Unknow" type="text" id="Author" data-ms-member="last-name" value="{{copy.note}}" /></div>
                <div class="flex-row_outer---custom">
                  <div class="input-wrapper"><label for="Type" class="input-label">Status</label>
                    <select id="Type" name="status" data-name="Type" data-ms-member="select" class="input-2 w-select">
                      {% if copy.status == 0 %}
                      <option value="0" selected>hidden</option>
                      <option value="1">available</option>
                      <option value="2">borrowed</option>
                      <option value="3">unavailable</option>
                      {% endif %}
                      {% if copy.status == 1 %}
                      <option value="0">hidden</option>
                      <option value="1" selected>available</option>
                      <option value="2">borrowed</option>
                      <option value="3">unavailable</option>
                      {% endif %}
                      {% if copy.status == 2 %}
                      <option value="0">hidden</option>
                      <option value="1">available</option>
                      <option value="2" selected>borrowed</option>
                      <option value="3">unavailable</option>
                      {% endif %}
                      {% if copy.status == 3 %}
                      <option value="0">hidden</option>
                      <option value="1">available</option>
                      <option value="2">borrowed</option>
                      <option value="3" selected>unavailable</option>
                      {% endif %}
                    </select></div>                  
                </div>  
                <div class="padding-button-block">
                  <div class="submit-button-book"><input type="submit"  class="btn-primary---save w-button" value="Edit" /></div>
                </div>
                <input type="hidden" name="bookID" value="{{bookID}}" id="id_bookID"><input type="hidden" name="userID" value="{{copy.userID}}" id="id_userID"><input type="hidden" name="regDate" value="{{copy.regDate}}" id="id_regDate">
              </form>
    
    
    
    
   

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/mod/modApply.html
{% extends 'base/base.html' %}


{% block content %}
{% include 'base/message.html' %}

<div class="container-default---login w-container">
  <div data-w-id="bffbe75b-d95c-3992-bdd3-befc9d0bd453" style="opacity: 1;" class="mg-bottom-48px---login">
    <div class="sign-in-form-block---brix w-form">


      <form action = "{% url 'mod:modApply' %}" id="wf-form-Sign-in-V1" name="wf-form-Sign-in-V1" data-name="Sign in V1" method="post" class="sign-in-form-v1---brix" data-wf-page-id="6635af3e5935deccf38319cc" data-wf-element-id="07381e2a-d17a-38e9-de5c-b7fc4244450c" aria-label="Sign in V1">  
        {% csrf_token %}     
        <div class="title-container---brix">
          <h2 class="heading-2---sign-in"> Book Moderator Application</h2>
          <p class="paragraph-52">Please fill your info to start your application</p>
        </div>           
     
        <div class="input-div---brix">
          <label for="phone" class="field-label---brix-2">Phone Number</label>
          {% if request.user.phoneNum %}
          <input class="input---brix phone-icon---brix w-input" maxlength="256" name="phone" data-name="Phone" placeholder="" type="text" id="phone" required="" value="{{request.user.phoneNum}}">
          {% else %}
          <input class="input---brix phone-icon---brix w-input" maxlength="256" name="phone" data-name="Phone" placeholder="Please provide your phone number" type="text" id="phone" required="" >
          {% endif %}
      </div>
      <div class="input-div---brix">
          <label for="address" class="field-label---brix-2">Address</label>
          {% if request.user.address %}
          <input class="input---brix address-icon---brix w-input" maxlength="256" name="address" data-name="Address" value="{{request.user.address}}" placeholder="your address" type="text" id="address" required="">
          {% else %}
          <input class="input---brix address-icon---brix w-input" maxlength="256" name="address" data-name="Address" placeholder="Please provide your address" type="text" id="address" required="">
          {% endif %}
      </div>
      <div class="input-div---brix">
          <label for="working_hours" class="field-label---brix-2">Available Working Hours (Write as a sentence)</label>
          {% if request.user.availableWorkingHours %}
          <input class="input---brix working-hours-icon---brix w-input" maxlength="256" name="working_hours" data-name="Working Hours" value="{{request.user.availableWorkingHours}}" type="text" id="working_hours" required="">
          {% else %}
          <input class="input---brix working-hours-icon---brix w-input" maxlength="256" name="working_hours" data-name="Working Hours" placeholder="Please provide your available hours" type="text" id="working_hours" required="">
          {% endif %}
      </div>
      <div class="input-div---brix-3">
          <label for="Desciptions" class="field-label---brix-2">Descriptions (Optional)</label>
          {% if request.user.description %}
          <textarea  placeholder="Let's introduce yourself to other users :)" maxlength="5000" id="Desciptions" name="description" data-name="Desciptions" class="text-area---brix w-input">{{request.user.description}}</textarea>
          {% else %}
          <textarea placeholder="Let's introduce yourself to other users :)" maxlength="5000" id="Desciptions" name="description" data-name="Desciptions" class="text-area---brix w-input"></textarea>
          {% endif %}
          
      </div>
      
      
                  <br><br>
                  <input type="submit" data-wait="Please wait..." class="log-in-button---brix w-button" value="Submit" />
        
        
          
        </form>

        
        


      </div>
    </div>
  </div>


{% endblock %}