Bibliotech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Pages for everyone (even guests)
    path('', include('home.urls')),

    # User pages
    path('user/', include('user.urls')),

    # For login using all-auth (OAuth2)
    path('accounts/', include('socialplatform.urls')),

    # Moderator pages
    path('mod/', include('moderator.urls')),

    # Admin (Control) pages
    path('control/', include('control.urls')),

    # Default django admin page
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    
handler404 = 'home.views.handling_404'

home/urls.py
from django.contrib import admin
from django.urls import path,include
from home.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'
urlpatterns = [
    path('', indexView.as_view(), name='index'),
    path('dashboard', dashboardView.as_view(), name="dashboard"),
    path("gallery", galleryView.as_view(), name="gallery"),
    path('gallery/bookid=<int:id>/detail',bookView.as_view(), name="book"),
    path('gallery/bookid=<int:id>/pdf', bookPDFView.as_view(), name="bookPDF"),
    path('shelf/userid=<int:id>',shelfView.as_view(), name = "shelf"),
    path('borrow/bookid=<int:id>',borrowView.as_view(), name = "borrow"),
    path('faq', faqView.as_view(), name='faq'),
    path('contact', contactView.as_view(), name='contact'),
    path('result', resultView.as_view(), name='result'),
]

moderator/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "mod"
urlpatterns = [
    path("", modView.as_view(), name='mod'),
    path("addBook", addBookView.as_view(), name='addBook'),
    path('editBook/bookid=<int:id>', editBookView.as_view(), name='editBook'),
    path('addCopy/bookid=<int:id>', addCopyView.as_view(), name='addCopy'),
    path('editCopy/copyid=<int:id>', editCopyView.as_view(), name="editCopy"),
    path('apply', applyModView.as_view(), name="modApply"),
    path('modManage',modManageView.as_view(), name="modManage_get"),
    path('modManage/<int:id>',modManageView.as_view(), name="modManage_post"),
    path('adminManage',adminManageView.as_view(), name="adminManage"),
    path('adminManage/<int:id>',adminManageView.as_view(), name="adminManage_post"),
    path('deleteBook/bookid=<int:id>',deleteBook,name='deleteBook'),
    # Do not uncomment "import"
    # This function is only used to automatically add book
    # path('import', importDataView.as_view(), name="import"),
]




if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, reverse_lazy
from user.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'
urlpatterns = [
    path('register/', registerView.as_view(), name="register"),
    path('login/', loginView.as_view(), name='login'),
    path('logout/', logoutView.as_view(), name='logout'),
    path("password", changePasswordView.as_view(), name="changePassword"),

    path("recover", recoverAccountView.as_view(), name="recover"),
    path("recover/sent", recoverDoneView.as_view(), name="recover_done"),
    path("recover/<uidb64>/<token>", recoverConfirmView.as_view(), name="recover_confirm"),
    path("recover/complete", recoverCompleteView.as_view(), name="recover_complete"),

    path("profile/info/", profileInfoRedirectView.as_view(), name="info"),
    path("profile/userID=<int:id>/", profileInfoView.as_view(), name="wall"),
    path("profile/borrow/", userBorrowanceManagerView.as_view(), name="borrow"),
    path("profile/edit/", profileEditView.as_view(), name="edit"),
    path("activate/<uidb64>/<token>", activate, name="activate"),
]

if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

# Create your models here.
def getBookImageURL(instance, filename):
  if instance.id != None:
      return "book/{}/coverImage.png".format(instance.id)
  else:
    queryset = Book.objects.all().order_by('pk')
    last = queryset.last()
    last_id = last.id
    file_number = last_id+1
    return "book/{}/coverImage.png".format(file_number)

def getBookPDFURL(instance, filename):
  if instance.id != None:
      return "book/{}/pdfFile.pdf".format(instance.id)
  else:
    queryset = Book.objects.all().order_by('pk')
    last = queryset.last()
    last_id = last.id
    file_number = last_id+1
    return "book/{}/pdfFile.pdf".format(file_number)

def getUserImageURL(instance, filename):
  if instance.id != None:
      return "user/{}/avatar.png".format(instance.id)
  else:
    queryset = User.objects.all().order_by('pk')
    last = queryset.last()
    last_id = last.id
    file_number = last_id+1
    return "user/{}/avatar.png".format(file_number)

class User(AbstractUser):
  email = models.EmailField(null=False, blank=False, unique=True, help_text="Required", error_messages="This field is compulsory and must follow email format")
  avatar = models.ImageField(upload_to=getUserImageURL, null=True, blank=True)
  birthdate = models.DateField(null=True, blank=True)
  genderChoices = (
    (0, "male"),
    (1, "female"),
    (2, "other")
  )
  gender = models.IntegerField(choices=genderChoices, null=False, default=2)
  address = models.CharField(max_length=200, null=True, blank=True)
  phoneNum = models.CharField(max_length=50, null=True, blank=True)
  roleChoices = (
    (0, "user"),
    (1, "moderator"),
    (2, "admin"),
    (3, "banned")
  )
  role = models.IntegerField(choices=roleChoices, default=0)
  description = models.CharField(max_length=1500, null=True, blank=True)
  availableWorkingHours = models.CharField(max_length=300, null=True, blank=True)

class Book(models.Model):
  title = models.CharField(max_length=200, null=False, default="UNTITLED")
  author = models.CharField(max_length=200, null=False, default="UNKNOWN")
  typeChoices = (
    (0, "article"),
    (1, "book"),
    (2, "magazine"),
    (3, "video/audio"),
    (4, "comic"),
    (5, "other")
  )
  type = models.IntegerField(choices=typeChoices, null=True, default=0)
  liteCate = models.BooleanField(default=False, blank=True, null=True)
  socieCate = models.BooleanField(default=False, blank=True, null=True)
  naturCate = models.BooleanField(default=False, blank=True, null=True)
  techCate = models.BooleanField(default=False, blank=True, null=True)
  poliCate = models.BooleanField(default=False, blank=True, null=True)
  romanCate = models.BooleanField(default=False, blank=True, null=True)
  enterCate = models.BooleanField(default=False, blank=True, null=True)
  otherCate = models.BooleanField(default=False, blank=True, null=True)
  language = models.CharField(max_length=200, null=True, blank=True)
  description = models.TextField(max_length=1500, null=True, blank=True)
  coverImage = models.ImageField(upload_to=getBookImageURL, null=True, blank=True)
  pdfFile = models.FileField(upload_to=getBookPDFURL,null=True,blank=True)
  publisher = models.CharField(max_length=200, null=True, blank=True)
  publication = models.CharField(max_length=50, null=True, blank=True)
  codeISBN = models.CharField(max_length=50, null=True, blank=True)
  statusChoices = (
    (0, "pending"),
    (1, "accepted"),
    (2, "rejected")
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=True)
  id = models.AutoField(primary_key=True)
  manual = models.BooleanField(default=True, null = True, blank = True)

  def __str__(self) :
    return str(self.id) + ". " + self.title


class Copy(models.Model):
  bookID = models.ForeignKey(Book, null=False, on_delete=models.CASCADE)
  userID = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
  statusChoices = (
    (0, "hidden"),
    (1, "available"),
    (2, "borrowed"),
    (3, "unavailable")
  )
  status = models.IntegerField(choices=statusChoices, default=0)
  note = models.TextField(max_length=200, null=True, blank=True)
  regDate = models.DateTimeField(null=False)

  def __str__(self) :
    return str(self.id) + ". " + self.bookID.title


class Borrowance(models.Model):
  copyID = models.ForeignKey(Copy, on_delete=models.CASCADE)
  userID = models.ForeignKey(User, on_delete=models.CASCADE)
  borrowDate = models.DateTimeField(null=False)
  expiredDate = models.DateTimeField(null=False)
  statusChoices = (
    (0, "request"),
    (1, "double-check"),
    (2, "borrowing"),
    (3, "returned"),
    (4, "overdue"),
    (5, "lost")
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=False)
  deposit = models.FloatField(default=0, null=True, blank=True)


class Review(models.Model):
  bookID = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='reviews')
  userID = models.ForeignKey(User, on_delete=models.CASCADE)

  def validateRating(value):
    if (value > 5 or value < 1):
      raise ValidationError(
        _('%(value)s is not valid'),
        params={'value': value},
      )
    
  rating = models.IntegerField(validators=[validateRating], null=True, blank=True)
  review = models.TextField(max_length=1500, null=True, blank=True)
  created_at = models.DateTimeField(default=timezone.now)

  def __str__(self) :
    return "Review " + str(self.id)
  
def getApplicantDocURL(instance, filename):
  return "user/{}/modApplication.pdf".format(instance.applicant.id)

class ModApplication(models.Model):
  applicant = models.ForeignKey(User, on_delete=models.CASCADE)
  applicantDocument = models.FileField(upload_to=getApplicantDocURL,null=True,blank=True)
  applicantText = models.TextField(max_length=1500, null=True, blank=True)
  adminComment = models.TextField(max_length=1500, null=True, blank=True)
  statusChoices = (
    (0, "applying"),
    (1, "approved"),
    (2, "denied"),
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=False)
  created_at = models.DateTimeField(default=timezone.now)
  
class Thought(models.Model):
  userID = models.ForeignKey(User, on_delete=models.CASCADE)
  thought = models.TextField(max_length=1500, null=False)
  created_at = models.DateTimeField(default=timezone.now)
  
class BookApplication(models.Model):
  bookID = models.ForeignKey(Book, on_delete=models.CASCADE)
  uploader = models.ForeignKey(User, on_delete=models.CASCADE)
  statusChoices = (
    (0, "applying"),
    (1, "approved"),
    (2, "denied"),
  )
  status = models.IntegerField(choices=statusChoices, default=0, null=False)
  created_at = models.DateTimeField(default=timezone.now)

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ValidationError

from home.models import Thought, User


class LoginForm(AuthenticationForm):
  class Meta:
    model = User
    fields = "__all__"


class RegisterForm(UserCreationForm):
  class Meta:
    model = User
    fields = ["username", "email", "password1", "password2",
              "first_name", "last_name", "birthdate", "gender",
              "address", "phoneNum"]
    # fields = "__all__"

  def clean(self):
    email = self.cleaned_data.get('email')
    if User.objects.filter(email=email).exists():
        raise ValidationError("Email exists")
    return self.cleaned_data

class ProfileEditForm(forms.ModelForm):

  class Meta:
    model = User
    fields = ["avatar", "first_name", "last_name", "birthdate", "gender",
              "address", "phoneNum"]
    
class ThoughtForm(forms.ModelForm):
  class Meta:
    model = Thought
    fields = "__all__"

templates/user/login.html
{% extends 'base/base.html' %}
{% block content %}
{% load socialaccount %}
{% load static %}
{% include 'base/message.html' %}



<div class="w-nav-overlay" data-wf-ignore="" id="w-nav-overlay-0"></div>
          <div class="container-default---login w-container">
            <div data-w-id="bffbe75b-d95c-3992-bdd3-befc9d0bd453" style="opacity: 1;" class="mg-bottom-48px---login">
              <div class="sign-in-form-block---brix w-form">

                {% for key, value in form.error.items %}
                {{value}}
                {% endfor %}


                <form action = "{% url 'user:login' %}" id="wf-form-Sign-in-V1" name="wf-form-Sign-in-V1" data-name="Sign in V1" method="post" class="sign-in-form-v1---brix" data-wf-page-id="6635af3e5935deccf38319cc" data-wf-element-id="07381e2a-d17a-38e9-de5c-b7fc4244450c" aria-label="Sign in V1">       
                  <div class="title-container---brix">
                    <h2 class="heading-2---sign-in">Login</h2>
                    <p class="paragraph-52">Please fill your email and password to login</p>
                  </div>           
                    {% csrf_token %}
                  <div class="input-div---brix"><input class="input---brix name-icon---brix w-input" maxlength="256" name="username" data-name="Username" placeholder="Username" type="text" id="username" required=""></div>
                  <div class="input-div---brix"><input class="input---brix password-icon---brix w-input" maxlength="256" name="password" data-name="Password" placeholder="Password" type="password" id="password" required=""></div>
                  <label id="remember-me-preview" class="w-checkbox checkbox-field---brix">
                    <style>
                      .w-checkbox-input--inputType-custom.w--redirected-checked {
                        background-color: #3898ec;
                        background-image: url("{% static 'base/custom-checkbox-checkmark.589d534424.svg' %}");
                        background-position: 50%;
                        background-repeat: no-repeat;
                        background-size: cover;
                        border-color: #3898ec;
                      }
                    </style>
                    <div class="w-checkbox-input w-checkbox-input--inputType-custom checkbox---brix"></div><input type="checkbox" id="Remember me" name="Remember-me" data-name="Remember me"  style="opacity:0;position:absolute;z-index:-1"><span for="Remember-me" class="w-form-label">Remember me</span>
                  </label>
                  <div class="create-account-box"><a href="{% url 'user:register' %}" class="create-new-account---brix">Don't have an account?&nbsp;Sign Up</a></div><input type="submit" data-wait="Please wait..." class="log-in-button---brix w-button" value="Login">    
                  <a href="{% url 'user:recover' %}" class="forgot-password---brix">Forgot your password?</a>                        
                  <div class="or-divider---brix">
                    <div class="stroke---brix"></div>
                    <div class="or-text-block---brix">or</div>
                    <div class="stroke---brix"></div>
                  </div> 
                  <div class="social-buttons-wrap---brix"><a href="{% provider_login_url 'google' %}" class="social-button---brix w-inline-block"><img src="{% static 'user/login/google.svg'%}" loading="lazy" alt="" class="social-small-logo---brix">
                      <div>Login with Google</div>
                    </a></div>
                  </form>               
              </div>
            </div>
          </div>
{% endblock %}

templates/user/passwordChange.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
{% include 'base/message.html' %}
  <style>
    .input-valid {
      border: 2px solid green;
    }
    .input-invalid {
      border: 2px solid red;
    }
    .condition-valid {
      color: green;
    }
    .condition-invalid {
      color: red;
    }
    .disabled-button {
      background-color: grey !important;
      cursor: not-allowed !important;
    }
  </style>
  <div style="opacity: 1;" class="page-wrapper">
    <div class="w-nav-overlay" data-wf-ignore="" id="w-nav-overlay-0"></div>
  </div>
  <div class="main-section">
    <div class="container-default w-container">
      <div class="block-sticky-top---main-contain">
        <div id="w-node-_5b7b5ab1-6d00-c7e0-62e6-f29490555c22-71edfef9" class="dashboard-main-content---user-profiles">
          <div id="cards" data-w-id="c25945b2-b467-1640-757f-35242a0cbdb5" style="opacity: 1; max-width: 95vw;" class="pd-top-24px---activities">
            <h2 class="text-500 bold mg-bottom-12px">Change Password</h2>
            <div class="card component-card card-one-line">
              <div class="w-form">
                
                <form action="{% url 'user:changePassword' %}" id="wf-form-signup" name="wf-form-signup" method="post" class="container_profile-form-2" aria-label="signup">
                  {% csrf_token %}
                  <div class="spacer_m"></div>
                  <div>Use this form to change your password.</div>
                  <div class="spacer_m"></div>
                  <div class="input-wrapper">
                    <label for="old_password" class="input-label">Current password</label>
                    <i class="fa-solid fa-eye" style="position: relative; left: 95%; top: 30px;" onclick="old_password_toggle()"></i>
                    <input class="input-2 w-input" maxlength="256" name="old_password" placeholder="" type="text" id="old_password" onclick="old_password_toggle()" required />
                  </div>
                  <div class="input-wrapper">
                    <label for="new_password1" class="input-label">New password</label>
                    <i class="fa-solid fa-eye" style="position: relative; left: 95%; top: 30px;" onclick="new_password_toggle()"></i>
                    <input class="input-2 w-input" maxlength="256" name="new_password1" placeholder="" type="text" id="new_password1" required />
                  </div>
                  <div class="input-wrapper">
                    <label for="new_password2" class="input-label">Repeat new password</label>
                    <i class="fa-solid fa-eye" style="position: relative; left: 95%; top: 30px;" onclick="repeat_password_toggle()"></i>
                    <input class="input-2 w-input" maxlength="256" name="new_password2" placeholder="" type="text" id="new_password2" onclick="repeat_password_toggle()" required />
                  </div>
                  <div class="description">
                    <em>
                      * Your password: <br />
                      <span id="lengthP" class="condition-invalid">&nbsp;&nbsp;&nbsp;&nbsp;has at least 8 characters.</span><br />
                      <span id="valid-charsP" class="condition-invalid">&nbsp;&nbsp;&nbsp;&nbsp;has a combination of letters, numbers, and symbols.</span><br/>
                      <span id="matchP" class="condition-invalid">&nbsp;&nbsp;&nbsp;&nbsp;matches the confirmation password.</span>
                    </em>
                  </div>
                  <div class="spacer_m"></div>
                  <div class="block-button">
                    <input type="submit" class="log-in-button---brix w-button disabled-button" id="change-password-button" value="Change Password" disabled>
                  </div>
                </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
    var lengthOK = false;
    var wordRegexOK = false;
    var confirmation = false;

    function checkChangePasswordButton() {
        const changePasswordButton = document.getElementById('change-password-button');
        if (lengthOK && wordRegexOK && confirmation) {
            changePasswordButton.disabled = false;
            changePasswordButton.classList.remove('disabled-button');
        } else {
            changePasswordButton.disabled = true;
            changePasswordButton.classList.add('disabled-button');
        }
    }

    document.getElementById('new_password1').addEventListener('input', function () {
        const passwordInput = this.value;
        const lengthP = document.getElementById('lengthP');
        const validCharsP = document.getElementById('valid-charsP');

        // Check length
        if (passwordInput.length >= 8) {
            lengthP.classList.remove('condition-invalid');
            lengthP.classList.add('condition-valid');
            lengthOK = true;
        } else {
            lengthP.classList.remove('condition-valid');
            lengthP.classList.add('condition-invalid');
            lengthOK = false;
        }

        // Check for valid characters
        const regex = /^(?=.*[a-zA-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]+$/;
        if (regex.test(passwordInput)) {
            validCharsP.classList.remove('condition-invalid');
            validCharsP.classList.add('condition-valid');
            wordRegexOK = true;
        } else {
            validCharsP.classList.remove('condition-valid');
            validCharsP.classList.add('condition-invalid');
            wordRegexOK = false;
        }

        checkChangePasswordButton();
    });

    document.getElementById('new_password2').addEventListener('input', function () {
        const passwordInput = document.getElementById('new_password1').value;
        const confirmationInput = this.value;
        const matchP = document.getElementById('matchP');

        // Check if passwords match
        if (passwordInput === confirmationInput) {
            matchP.classList.remove('condition-invalid');
            matchP.classList.add('condition-valid');
            confirmation = true;
        } else {
            matchP.classList.remove('condition-valid');
            matchP.classList.add('condition-invalid');
            confirmation = false;
        }

        checkChangePasswordButton();
    });
    function old_password_toggle() {
      var x = document.getElementById("old_password");
      if (x.type === "password") {
        x.type = "text";
      } else {
        x.type = "password";
      }
    }
    function new_password_toggle() {
      var x = document.getElementById("new_password1");
      if (x.type === "password") {
        x.type = "text";
      } else {
        x.type = "password";
      }
    }
    function repeat_password_toggle() {
      var x = document.getElementById("new_password2");
      if (x.type === "password") {
        x.type = "text";
      } else {
        x.type = "password";
      }
    }
  </script>
  <br><br><br>
{% endblock %}

templates/user/profileEdit.html
{% extends 'base/base.html' %}
{% load static %}


{% block content %}

<style>
  .btn-secondary---upload-new-avatar {
    display: inline-block;
    cursor: pointer;
  }
  
  input[type="file"] {
    display: none;
  }
</style>
<form action="{% url 'user:edit' %}" enctype="multipart/form-data" id="wf-form-signup" name="wf-form-signup" data-name="signup" method="post" data-ms-form="profile" class="container_profile-form-2" data-wf-page-id="6628cf5c13254dbc828fa890" data-wf-element-id="b9e108e9-0263-f841-ba73-fcf95b875e62" aria-label="signup">
  {% csrf_token %}
<div style="opacity: 1;" class="page-wrapper">
  <div class="main-section" style = "margin: 0 auto;">
    <div class="container-default w-container">
      <div class="block-sticky-top---main-contain">
        <div id="w-node-_5b7b5ab1-6d00-c7e0-62e6-f29490555c22-828fa890" class="dashboard-main-content---user-profiles">
          <div id="cards" data-w-id="c25945b2-b467-1640-757f-35242a0cbdb5" style="opacity: 1;" class="pd-top-24px---activities">
            <h2 class="text-500 bold mg-bottom-12px">Your profile info</h2>
            <div class="card component-card card-one-line" style="max-width: 95vw">
              <div class="block-of-avatar">
                <div class="block-of-your-avatar">
                  <div class="div-block-10">

                    {% if socialAccount %}
                    <img src="{{ socialAccount.get_avatar_url }}" loading="eager" sizes="(max-width: 1439px) 48px, 81px"  alt="Avatar - Dashflow X Webflow Template" class="avatar-circle _81px">
                    {% else %}
                      
                      {% if user.avatar %}
                      <img src="/media/{{ user.avatar }}" loading="eager" sizes="(max-width: 1439px) 48px, 81px"  alt="Avatar - Dashflow X Webflow Template" class="avatar-circle _81px">
                     
                      {% else %}
                      <img src="/media/user/defaultAvatar.jpg" loading="eager" sizes="(max-width: 1439px) 48px, 81px"  alt="Avatar - Dashflow X Webflow Template" class="avatar-circle _81px">
                      {% endif %}
                    {% endif %}
                    <div class="block-combo-your-avatar">
                      <h1 class="h1_small-your-avatar">Your Avatar</h1>
                      <div>Profile picture of any size!</div>
                    </div>
                  </div>
                  {% comment %} <div data-w-id="0b4af8e5-0116-a75e-1b7c-69e354dadc56" class="save-avatar-button"><a data-w-id="5237d547-6605-a6a5-bc8b-bb8090bf390c" href="https://final-teamplate.webflow.io/user/user-change-profile#" class="btn-primary---save w-inline-block">
                      <div class="flex-horizontal gap-column-4px">
                        <div>Save Avatar</div>
                      </div>
                    </a></div> {% endcomment %}
                    <div data-w-id="1de72452-8b8b-2823-d65d-ac9efe469afc" class="upload-new-avatar-button">
                      <label for="id_avatar" class="btn-secondary---upload-new-avatar w-inline-block">
                        <input type="file" enctype="multipart/form-data"  name="avatar" style="display: none;" accept="image/*" id="id_avatar">
                        <div class="flex-horizontal gap-column-4px">
                          <div class="text-size">
                            <strong>Upload new avatar</strong>
                          </div>
                        </div>
                      </label>
                    </div>

                </div>
                
              </div>
              <div id="general-form" general-form=".my-form {display:block !important;}" class="w-form">
                
                
                  
                 
                  
                  
                  <div class="flex-row_outer">
                    <div class="input-wrapper _15p-right"><label for="first_name" class="input-label">First Name</label><input class="input-2 w-input" maxlength="256" name="first_name" data-name="First Name 4" value="{{user.first_name}}" type="text" id="id_first_name" data-ms-member="first-name" placeholder="Your first name"></div>
                    <div class="input-wrapper"><label for="last_name" class="input-label">Last Name</label><input class="input-2 w-input" maxlength="256" name="last_name" data-name="Last Name 4" value="{{user.last_name}}" placeholder="Your last name" type="text" id="id_last_name" data-ms-member="last-name" ></div>
                  </div>
      
                  <div class="flex-row_outer">
                    <div class="input-wrapper _15p-right"><label for="birthdate" class="input-label">Birthdate</label><input type="date" class="input-2 w-input" maxlength="256" name="birthdate" data-name="birthdate" id="id_birthdate" data-ms-member="first-name" value="{{birthdate}}"></div>
                    {% if user.phoneNum != None %}
                    <div class="input-wrapper"><label for="phoneNum" class="input-label">Phone Number</label><input class="input-2 w-input" maxlength="256" name="phoneNum" data-name="Phone Number" value="{{user.phoneNum}}" placeholder="Your phone number" type="text" id="id_phoneNum" data-ms-member="last-name" ></div>
                    {% else %}
                    <div class="input-wrapper"><label for="phoneNum" class="input-label">Phone Number</label><input class="input-2 w-input" maxlength="256" name="phoneNum" data-name="Phone Number"  placeholder="Your phone number" type="text" id="id_phoneNum" data-ms-member="last-name" ></div>
                    {% endif %}
                  </div>
                  <div class="flex-row_outer">
                    {% if user.address != None %}
                    <div class="input-wrapper _15p-right"><label for="address" class="input-label">Address</label><input class="input-2 w-input" maxlength="256" name="address" data-name="Phone 2" value="{{user.address}}" placeholder="Your address" type="text" id="id_address" data-ms-member="phone"  ></div>
                    {% else %}
                    <div class="input-wrapper _15p-right"><label for="address" class="input-label">Address</label><input class="input-2 w-input" maxlength="256" name="address" data-name="Phone 2"  placeholder="Your address" type="text" id="id_address" data-ms-member="phone"  ></div>
                    {% endif %}
                    <div class="input-wrapper"><label for="gender" class="input-label">Gender</label><select id="id_gender" name="gender" data-name="Field 2" data-ms-member="select" class="input-2---gender w-select">
                        {% if user.gender == 0 %}
                        <option value="0">Male</option>
                        <option value="1">Female</option>
                        <option value="2">Others</option>
                        {% else %}
                          {% if user.gender == 1 %}
                          <option value="1">Female</option>
                          <option value="0">Male</option>
                          <option value="2">Others</option>
                          {% else %}
                          <option value="2">Others</option>
                          <option value="0">Male</option>
                          <option value="1">Female</option>
                          {% endif %}
                        {% endif %}
                      </select></div>
                    </div>
                  </div>
                  
              <div data-w-id="1b801390-716a-d15f-f79d-f9272e217625" class="block-save-profile-button">
                <br>
                <button data-w-id="40c92f68-ad9b-f6ff-b252-85434513c111" class="btn-primary---save w-button">Save changes</button>
              </div>
            
            
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</form>
{% endblock %}

templates/user/template_activate_account.html
{% autoescape off %}
Hi {{user.username }},
Please click on the link below to confirm your registration:

http://vgupe2024team2clone-production.up.railway.app{% url 'user:activate' uidb64=uid token=token %}
{% endautoescape %}